# -*- coding: utf-8 -*-
"""applstock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RI1HLrrCgoZH57nh9iy-QlO2dGvFu1au
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



# 1. Load data
df = pd.read_csv("/content/drive/MyDrive/AAPL.csv")
df

# 2. Understand data
print(df.head())

print(df.shape)

print(df.info())

# 4. Check missing values
print(df.isnull().sum())

df = df.dropna()

# 5. Remove duplicates
df = df.drop_duplicates()
df

df = df.dropna()

# 5. Remove duplicates
df = df.drop_duplicates()
df

# 4. Check missing values
print(df.isnull().sum())

df = df.dropna()

# 5. Remove duplicates
df = df.drop_duplicates()
df

# 10. Volume analysis

average_volume = df["Volume"].mean()
maximum_volume = df["Volume"].max()
minimum_volume = df["Volume"].min()

print("Average Volume:", average_volume)
print("Maximum Volume:", maximum_volume)

"""## Analyze the stock prices"""

# Resample to monthly average of 'Close' price
monthly_avg_close = df['Close'].resample('ME').mean()

display(monthly_avg_close.head())

# Plotting the monthly average close price
plt.figure(figsize=(12, 6))
monthly_avg_close.plot(title='Monthly Average Close Price')
plt.xlabel('Date')
plt.ylabel('Average Close Price')
plt.grid(True)
plt.show()